import Product from '@/components/Home/Product';
import React from 'react';

export const metadata = {
    title:"All Products",
    description:"Generated by create next app"
}

const Productspage = () => {

    return (
        <div>
             <Product/>
        </div>
    );
};

export default Productspage;